version: '3.9'

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis

  app:
    build: .
    command: sh -c "python app.py"
    ports:
      - "5001:5001"
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@postgres:5432/postgres
      CELERY_BROKER_URL: "redis://redis:6379/0"
    volumes:
      - app_data:/app/uploaded-files/
    depends_on:
      - postgres
      - celery

  celery:
    build: .
    command: sh -c "celery -A app.celery_app worker --loglevel=info"
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@postgres:5432/postgres
      CELERY_BROKER_URL: "redis://redis:6379/0"
    volumes:
      - app_data:/app/uploaded-files/
    depends_on:
      - redis
      - postgres

  flower:
    build: .
    command: sh -c "celery -A app.celery_app flower --port=5555"
    ports:
      - "5555:5555"
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@postgres:5432/postgres
      CELERY_BROKER_URL: "redis://redis:6379/0"
    depends_on:
      - celery

volumes:
  app_data: